// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HafizDemoAPI.ModelCDN
{
    public partial class CDNUserConn
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string ConnectionId { get; set; }
        public bool Connected { get; set; }
        public DateTime? DateConnect { get; set; }
    }
}