name: Build and deploy ASP.Net Core app to Azure Web App - hafiz-cdn

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build HafizDemoAPI.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish HafizDemoAPI.sln -c Release -o out

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: hafiz-cdn
          path: ./out   # Change this path to match your published files

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: hafiz-cdn

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hafiz-cdn'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2C95EC2579874FF0BF5C08B2AAA782FC }}
          package: ./  # Change this path to match your published files on Azure
